# Generated by Django 3.2.3 on 2021-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(max_length=280),
        ),
    ]
