# Generated by Django 3.2.3 on 2021-08-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_entry_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='time',
        ),
    ]
